### ISSUE TITLE
how much gpu-memory is needed to train freebase?

### ISSUE THREAD

**Issue by zhixiaochuan12** [THUDM/HGB#6]
I used a 32g V100 to train RGCN on freebase dataset, but get the following error:

> Using backend: pytorch
> begin: 4194304
> Traceback (most recent call last):
>   File "entity_classify.py", line 354, in <module>
>     main(args)
>   File "entity_classify.py", line 187, in main
>     features_list = [mat2tensor(features).to(device)
>   File "entity_classify.py", line 187, in <listcomp>
>     features_list = [mat2tensor(features).to(device)
> RuntimeError: CUDA out of memory. Tried to allocate 25.27 GiB (GPU 0; 31.75 GiB total capacity; 7.50 GiB already allocated; 23.21 GiB free; 7.51 GiB reserved in total by PyTorch)

The command line is `python entity_classify.py --dataset=freebase -e 150 --gpu=0`

**Comment by cyx233** [comment]
Well, I finally trained FreeBase by CPU. As far as I know, it needs more than 30G GPU memory. 
However, the codes have been modified and there are some conflicts. For example, File entity_classifier.py, line 236, "g = g.to('cuda:%d' % args.gpu)", it should be modified to "g = g.to(device)" if you want to train models by CPU.

**Comment by cyx233** [comment]
> I used a 32g V100 to train RGCN on freebase dataset, but get the following error:
> 
> > Using backend: pytorch
> > begin: 4194304
> > Traceback (most recent call last):
> > File "entity_classify.py", line 354, in 
> > main(args)
> > File "entity_classify.py", line 187, in main
> > features_list = [mat2tensor(features).to(device)
> > File "entity_classify.py", line 187, in 
> > features_list = [mat2tensor(features).to(device)
> > RuntimeError: CUDA out of memory. Tried to allocate 25.27 GiB (GPU 0; 31.75 GiB total capacity; 7.50 GiB already allocated; 23.21 GiB free; 7.51 GiB reserved in total by PyTorch)
> 
> The command line is `python entity_classify.py --dataset=freebase -e 150 --gpu=0`

Well, I finally trained FreeBase by CPU. As far as I know, it needs more than 30G GPU memory.
However, the codes have been modified and there are some conflicts. For example, File entity_classifier.py, line 236, "g = g.to('cuda:%d' % args.gpu)", it should be modified to "g = g.to(device)" if you want to train models by CPU.

**Comment by cyx233** [comment]
> I used a 32g V100 to train RGCN on freebase dataset, but get the following error:
> 
> > Using backend: pytorch
> > begin: 4194304
> > Traceback (most recent call last):
> > File "entity_classify.py", line 354, in 
> > main(args)
> > File "entity_classify.py", line 187, in main
> > features_list = [mat2tensor(features).to(device)
> > File "entity_classify.py", line 187, in 
> > features_list = [mat2tensor(features).to(device)
> > RuntimeError: CUDA out of memory. Tried to allocate 25.27 GiB (GPU 0; 31.75 GiB total capacity; 7.50 GiB already allocated; 23.21 GiB free; 7.51 GiB reserved in total by PyTorch)
> 
> The command line is `python entity_classify.py --dataset=freebase -e 150 --gpu=0`
Well, I finally trained FreeBase by CPU. As far as I know, it needs more than 35G GPU memory.
However, the codes have been modified and there are some conflicts. For example, File entity_classifier.py, line 236, "g = g.to('cuda:%d' % args.gpu)", it should be modified to "g = g.to(device)" if you want to train models by CPU.

**Comment by cyx233** [comment]
> I used a 32g V100 to train RGCN on freebase dataset, but get the following error:
> 
> > Using backend: pytorch
> > begin: 4194304
> > Traceback (most recent call last):
> > File "entity_classify.py", line 354, in 
> > main(args)
> > File "entity_classify.py", line 187, in main
> > features_list = [mat2tensor(features).to(device)
> > File "entity_classify.py", line 187, in 
> > features_list = [mat2tensor(features).to(device)
> > RuntimeError: CUDA out of memory. Tried to allocate 25.27 GiB (GPU 0; 31.75 GiB total capacity; 7.50 GiB already allocated; 23.21 GiB free; 7.51 GiB reserved in total by PyTorch)
> 
> The command line is `python entity_classify.py --dataset=freebase -e 150 --gpu=0`

Well, I finally trained FreeBase by CPU. As far as I know, it needs more than 35G GPU memory.
However, the codes have been modified and there are some conflicts. For example, File entity_classifier.py, line 236, "g = g.to('cuda:%d' % args.gpu)", it should be modified to "g = g.to(device)" if you want to train models by CPU.

**Comment by zhixiaochuan12** [comment]
ok, thanks.
